dist: xenial
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=lint

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox

after_success:
  - codecov -e TOX_ENV
